CREATE TABLE `user` (
  `ID` varchar(100) NOT NULL,
  `FULL_NAME` varchar(255) DEFAULT NULL,
  `PHONE` varchar(20) NOT NULL,
  `REFERRAL_CODE` varchar(255) DEFAULT NULL,
  `PARENT_ID` varchar(100) DEFAULT NULL,
  `H_LEVEL` int NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PHONE` (`PHONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci